export const POST_LIST_LOAD_PENDING: string = 'POST_LIST_LOAD_PENDING';
export const POST_LIST_LOAD_SUCCESS: string = 'POST_LIST_LOAD_SUCCESS';
export const POST_LIST_LOAD_FAILED: string = 'POST_LIST_LOAD_FAILED';